### PR TITLE
Move to llvm 16

### PR DESCRIPTION
**Pull request by seanyoung**

### CODE REVIEW

**Review by xermicus — APPROVED** [review]
It looks like we can use the solana labs LLVM fork for `rv32e` too but we need to apply the patches and build the compiler runtime.

**Comment by xermicus** [comment]
@seanyoung do we want to merge this first and I make another PR with riscv or how do proceed?

**Comment by seanyoung** [comment]
> @seanyoung do we want to merge this first and I make another PR with riscv or how do proceed?

Yeah let's merge this first. @LucasSte?

**Review by LucasSte — APPROVED** [review]

**Comment by LucasSte** [comment]
> > @seanyoung do we want to merge this first and I make another PR with riscv or how do proceed?
> 
> Yeah let's merge this first. @LucasSte?

Let's merge this one first and ensure it works with Solang.

**Pull request merged**
